/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import Frame.Koneksi;
import Frame.login;

/**
 *
 * @author nizarislamudin
 */
public class daftar_akun extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public daftar_akun() {
        
        initComponents();
         autonumber();
    }
    
    private void autonumber(){
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM login ORDER BY id DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String NoID = r.getString("id").substring(2);
                String ID = "" +(Integer.parseInt(NoID)+1);
                String Zero = "";
                
                if (ID.length()==1) 
                {Zero = "00";}
                else if(ID.length()==2)
                {Zero = "0";}
                else if(ID.length()==3)
                {Zero = "";}
                
                txID.setText("AD" + Zero + ID);
            }else{
                txID.setText("AD001");
            }
            r.close();
            s.close();
        }catch(Exception e){
            System.out.println("autonumber error");
        }
    }
    
    private void daftar(){
        String id = txID.getText().toString().trim();
        String username = txUsername.getText().toString().trim();
        String gmail=txGmail.getText().toString().trim();
        String password = txPassword.getText().toString().trim();
        String conPassword = txConPassword.getText().toString().trim();
        String level = txLevel.getText().toString().trim();
        
        if (!password.equals(conPassword)){
            JOptionPane.showMessageDialog(null, "Kata Sandi Tidak Cocok");
         }else if (password.equals("") || username.equals("")){
            JOptionPane.showMessageDialog(null, "Username dan Password Tidak Boleh Kososng");
        }else{
            try{
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO login VALUES (?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id);
                p.setString(2, gmail);
                p.setString(3, username);
                p.setString(4, password);
                p.setString(5, level);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Berhasil Membuat Akun");
            }catch(SQLException e){
                System.out.println("Error");
            }finally{
                this.dispose();
                login a = new login();
                a.setVisible(true);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SelamatDatang = new javax.swing.JLabel();
        txLevel = new javax.swing.JTextField();
        txID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        FormBuatAkun = new javax.swing.JPanel();
        txPassword = new javax.swing.JTextField();
        txConPassword = new javax.swing.JTextField();
        Nama = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        KonPassword = new javax.swing.JLabel();
        buttonbatal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buttondaftar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        SelamatDatang1 = new javax.swing.JLabel();
        txGmail = new javax.swing.JTextField();
        Password1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        IllustrationPic = new javax.swing.JLabel();

        SelamatDatang.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        SelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setText("Selamat Datang");

        txLevel.setBackground(new java.awt.Color(0, 38, 165));
        txLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txLevel.setForeground(new java.awt.Color(255, 255, 255));
        txLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txLevel.setText("TELLER");
        txLevel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txLevel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txLevel.setFocusable(false);

        txID.setBackground(new java.awt.Color(0, 38, 165));
        txID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txID.setForeground(new java.awt.Color(255, 255, 255));
        txID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txID.setText(" ");
        txID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txID.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/income.png")).getImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        FormBuatAkun.setBackground(new java.awt.Color(0, 38, 165));

        txPassword.setBackground(new java.awt.Color(0, 38, 165));
        txPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txPassword.setForeground(new java.awt.Color(255, 255, 255));
        txPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPasswordActionPerformed(evt);
            }
        });

        txConPassword.setBackground(new java.awt.Color(0, 38, 165));
        txConPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txConPassword.setForeground(new java.awt.Color(255, 255, 255));
        txConPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        Nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nama.setForeground(java.awt.Color.white);
        Nama.setText("Nama");

        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setForeground(java.awt.Color.white);
        Password.setText("Password");

        KonPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KonPassword.setForeground(java.awt.Color.white);
        KonPassword.setText("Konfirmasi Password Anda");

        buttonbatal.setBackground(new java.awt.Color(69, 90, 100));
        buttonbatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonbatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonbatalMouseExited(evt);
            }
        });
        buttonbatal.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BATAL");
        buttonbatal.add(jLabel7, new java.awt.GridBagConstraints());

        buttondaftar.setBackground(new java.awt.Color(69, 90, 100));
        buttondaftar.setForeground(new java.awt.Color(255, 255, 255));
        buttondaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttondaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttondaftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttondaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttondaftarMouseExited(evt);
            }
        });
        buttondaftar.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DAFTAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 30, 6, 30);
        buttondaftar.add(jLabel6, gridBagConstraints);

        txUsername.setBackground(new java.awt.Color(0, 38, 165));
        txUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txUsername.setForeground(new java.awt.Color(255, 255, 255));
        txUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsernameActionPerformed(evt);
            }
        });

        SelamatDatang1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        SelamatDatang1.setForeground(new java.awt.Color(255, 255, 255));
        SelamatDatang1.setText("Buat Akun");

        txGmail.setBackground(new java.awt.Color(0, 38, 165));
        txGmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txGmail.setForeground(new java.awt.Color(255, 255, 255));
        txGmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGmailActionPerformed(evt);
            }
        });

        Password1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password1.setForeground(java.awt.Color.white);
        Password1.setText("Gmail");

        javax.swing.GroupLayout FormBuatAkunLayout = new javax.swing.GroupLayout(FormBuatAkun);
        FormBuatAkun.setLayout(FormBuatAkunLayout);
        FormBuatAkunLayout.setHorizontalGroup(
            FormBuatAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormBuatAkunLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(SelamatDatang1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FormBuatAkunLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(FormBuatAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password1)
                    .addGroup(FormBuatAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormBuatAkunLayout.createSequentialGroup()
                            .addComponent(buttondaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(KonPassword)
                        .addComponent(Nama)
                        .addComponent(Password)
                        .addComponent(txConPassword)
                        .addComponent(txPassword)
                        .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txGmail)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        FormBuatAkunLayout.setVerticalGroup(
            FormBuatAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormBuatAkunLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(SelamatDatang1)
                .addGap(25, 25, 25)
                .addComponent(Nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KonPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txConPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormBuatAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttondaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        IllustrationPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/Sign up-amico.png"))); // NOI18N
        IllustrationPic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IllustrationPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IllustrationPic, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(FormBuatAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FormBuatAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttondaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttondaftarMouseClicked
        daftar();
    }//GEN-LAST:event_buttondaftarMouseClicked

    private void buttondaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttondaftarMouseEntered
        // TODO add your handling code here:
        buttondaftar.setBackground(new Color (0,0,0));
    }//GEN-LAST:event_buttondaftarMouseEntered

    private void buttondaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttondaftarMouseExited
        buttondaftar.setBackground(new Color (69,90,100));
    }//GEN-LAST:event_buttondaftarMouseExited

    private void buttonbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbatalMouseClicked
        this.dispose();
    }//GEN-LAST:event_buttonbatalMouseClicked

    private void buttonbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbatalMouseEntered
        buttonbatal.setBackground(new Color (0,0,0));
    }//GEN-LAST:event_buttonbatalMouseEntered

    private void buttonbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbatalMouseExited
        buttonbatal.setBackground(new Color (69,90,100));    
    }//GEN-LAST:event_buttonbatalMouseExited

    private void txPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPasswordActionPerformed

    private void txUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsernameActionPerformed

    private void txGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txGmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormBuatAkun;
    private javax.swing.JLabel IllustrationPic;
    private javax.swing.JLabel KonPassword;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel SelamatDatang1;
    private javax.swing.JPanel buttonbatal;
    private javax.swing.JPanel buttondaftar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txConPassword;
    private javax.swing.JTextField txGmail;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txLevel;
    private javax.swing.JTextField txPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
