/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import net.proteanit.sql.DbUtils;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nizarislamudin
 */
public class input_gaji extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    PreparedStatement pst;
    Statement statLgn;

    /**
     * Creates new form INPUT_TELLER
     */
public input_gaji() {
        initComponents();
        koneksi();
        tabel();
        comboboxdatabase();
        
        tabeldatajabatan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabeldatajabatan.getTableHeader().setOpaque(false);
}
    
private void koneksi() {
	try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:/db_bluescope","root","");
            stat=con.createStatement();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
}
    
private void reset(){
        txGajiPokok.setText(null);
        txGajiLembur.setText(null);
}
 
private void tabel(){
    DefaultTableModel tb= new DefaultTableModel();
        // Memberi nama pada setiap kolom tabel
        tb.addColumn("JABATAN");
        tb.addColumn("GAJI POKOK");
        tb.addColumn("GAJI LEMBUR");
        tabeldatajabatan.setModel(tb);
    try{
        // Mengambil data dari database
        res=stat.executeQuery("select * from data_gaji");

            while (res.next())
            {
            // Mengambil data dari database berdasarkan nama kolom pada tabel
            // Lalu di tampilkan ke dalam JTable
            tb.addRow(new Object[]{
            res.getString("jabatan"),
            res.getString("gajipokok"),
            res.getString("gajilembur")
            });
        }

    }catch (Exception e){
    }
} 
private void comboboxdatabase(){
    try{
        String query="select * from data_jabatan";
        pst=con.prepareStatement(query);
        res=pst.executeQuery();
        
        while(res.next()){
        String nama_jabatan=res.getString("jabatan");
        txJabatan.addItem(nama_jabatan);
        }
    }catch(Exception e){
    }
    }
    
    private void simpan(){
        try{
            koneksi();
            statLgn = con.createStatement();
            String SQL = "insert into data_gaji values('"
                    +'0'+"','"
                    +txJabatan.getSelectedItem()+"','"
                    +txGajiPokok.getText()+"','"
                    +txGajiLembur.getText()+"')";
            statLgn.executeUpdate(SQL);
            tabel();
            statLgn.close();
            con.close();
            reset();
            JOptionPane.showMessageDialog(null, "Berhasil Memasukkan");
            
    }catch(SQLException exc){
        System.err.println(exc.getMessage());
    }
}
    
private void edit(){
    try{
            koneksi();
            statLgn = con.createStatement();
            String SQL = "UPDATE data_gaji SET id ='"+txID.getText()+"',"
                    + "jabatan = '"+txJabatan.getSelectedItem()+"', "
                    + "gajipokok = '"+txGajiPokok.getText()+"', "
                    + "gajilembur = '"+txGajiLembur.getText()+"' "
                    + "WHERE id = '"+txID.getText()+"'";
            statLgn.executeUpdate(SQL);
            tabel();
            statLgn.close();
            con.close();
            reset();
            JOptionPane.showMessageDialog(null, "Berhasil Merubah");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }    

}

private void hapus() {
     try{
            koneksi();
            statLgn = con.createStatement();
            String SQL = "DELETE FROM data_gaji WHERE jabatan = '"+txJabatan.getSelectedItem()+"'";
            statLgn.executeUpdate(SQL);
            tabel();
            statLgn.close();
            con.close();
            reset();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tmblbatal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldatajabatan = new javax.swing.JTable();
        txGajiPokok = new javax.swing.JTextField();
        txGajiLembur = new javax.swing.JTextField();
        txJabatan = new javax.swing.JComboBox<>();
        tombolsimpan = new rojerusan.RSMaterialButtonRectangle();
        tomboledit = new rojerusan.RSMaterialButtonRectangle();
        tombolhapus = new rojerusan.RSMaterialButtonRectangle();
        tombolreset = new rojerusan.RSMaterialButtonRectangle();
        SelamatDatang2 = new javax.swing.JLabel();
        SelamatDatang3 = new javax.swing.JLabel();
        panelRound1 = new Custom_Palette_Class.PanelRound();
        panelRound2 = new Custom_Palette_Class.PanelRound();
        jabatan = new javax.swing.JLabel();
        pokok = new javax.swing.JLabel();
        lembur = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tmblbatal1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        tmblbatal.setBackground(new java.awt.Color(204, 0, 0));
        tmblbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tmblbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmblbatalMouseClicked(evt);
            }
        });
        tmblbatal.setLayout(new java.awt.GridBagLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        tmblbatal.add(jLabel9, new java.awt.GridBagConstraints());

        txID.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/income.png")).getImage());
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tabeldatajabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldatajabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatajabatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldatajabatan);

        txGajiPokok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txGajiPokok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        txGajiPokok.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txGajiPokok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txGajiPokokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txGajiPokokMouseExited(evt);
            }
        });

        txGajiLembur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txGajiLembur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        txGajiLembur.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txGajiLembur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txGajiLemburMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txGajiLemburMouseExited(evt);
            }
        });

        txJabatan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txJabatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txJabatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txJabatanMouseExited(evt);
            }
        });

        tombolsimpan.setBackground(new java.awt.Color(0, 26, 114));
        tombolsimpan.setText("SIMPAN");
        tombolsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsimpanActionPerformed(evt);
            }
        });

        tomboledit.setBackground(new java.awt.Color(0, 26, 114));
        tomboledit.setText("EDIT");
        tomboledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboleditActionPerformed(evt);
            }
        });

        tombolhapus.setBackground(new java.awt.Color(0, 26, 114));
        tombolhapus.setText("HAPUS");
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });

        tombolreset.setBackground(new java.awt.Color(0, 26, 114));
        tombolreset.setText("RESET");
        tombolreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolresetActionPerformed(evt);
            }
        });

        SelamatDatang2.setFont(new java.awt.Font("Gilroy ExtraBold", 1, 24)); // NOI18N
        SelamatDatang2.setForeground(new java.awt.Color(0, 26, 114));
        SelamatDatang2.setText("Input Data Gaji");

        SelamatDatang3.setFont(new java.awt.Font("Gilroy ExtraBold", 1, 24)); // NOI18N
        SelamatDatang3.setForeground(new java.awt.Color(0, 26, 114));
        SelamatDatang3.setText("Tabel Data Gaji");

        panelRound1.setBackground(new java.awt.Color(225, 225, 225));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        panelRound2.setBackground(new java.awt.Color(225, 225, 225));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jabatan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jabatan.setForeground(new java.awt.Color(153, 153, 153));
        jabatan.setText("Jabatan");

        pokok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pokok.setForeground(new java.awt.Color(153, 153, 153));
        pokok.setText("Gaji Pokok");

        lembur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lembur.setForeground(new java.awt.Color(153, 153, 153));
        lembur.setText("Gaji Lembur/Jam");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tutorial Singkat");

        jLabel2.setText("1. Tetapkanlah gaji sesuai dengan jabatan lalu");

        jLabel3.setText("masukan pada kolom yang tersedia.");

        jLabel4.setText("2. Anda bisa merubah/hapus data dengan cara");

        jLabel5.setText("menekan data yang mau di rubah/ hapus");

        jLabel7.setText("pada tabel yang tersedia lalu rubah data dan");

        jLabel8.setText("tekan edit begitu pula untuk hapus.");

        jLabel16.setText("3. Untuk menghapus kolom yang terisi");

        jLabel17.setText("tekan tombol reset.");

        tmblbatal1.setBackground(new java.awt.Color(204, 0, 0));
        tmblbatal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tmblbatal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmblbatal1MouseClicked(evt);
            }
        });
        tmblbatal1.setLayout(new java.awt.GridBagLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        tmblbatal1.add(jLabel10, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelamatDatang3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jabatan)
                                        .addGap(218, 218, 218)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pokok))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lembur)
                                    .addComponent(txGajiLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tombolsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolreset, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel17)))))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SelamatDatang2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tmblbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(SelamatDatang2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tmblbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lembur)
                            .addComponent(pokok)
                            .addComponent(jabatan))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txGajiLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tombolsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tombolreset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelamatDatang3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel17)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1032, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabeldatajabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatajabatanMouseClicked
        // TODO add your handling code here:
        try {
            koneksi();
            int row =tabeldatajabatan.getSelectedRow();
            String tabel_klik=(tabeldatajabatan.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from data_gaji where jabatan='"+tabel_klik+"'");
            if(sql.next()){
                String ID = sql.getString("id");
                txID.setText(ID);
                String JABATAN = sql.getString("jabatan");
                txJabatan.setSelectedItem(JABATAN);
                String pokok = sql.getString("gajipokok");
                txGajiPokok.setText(pokok);
                String lembur = sql.getString("gajilembur");
                txGajiLembur.setText(lembur);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tabeldatajabatanMouseClicked

    private void tombolsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsimpanActionPerformed
        simpan();
    }//GEN-LAST:event_tombolsimpanActionPerformed

    private void tomboleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboleditActionPerformed
        edit();
    }//GEN-LAST:event_tomboleditActionPerformed

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        hapus();
    }//GEN-LAST:event_tombolhapusActionPerformed

    private void tombolresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolresetActionPerformed
        reset();
    }//GEN-LAST:event_tombolresetActionPerformed

    private void tmblbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmblbatalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tmblbatalMouseClicked

    private void tmblbatal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmblbatal1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tmblbatal1MouseClicked

    private void txGajiLemburMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txGajiLemburMouseEntered
        lembur.setForeground(new Color (25,25,25));
        txGajiLembur.setBorder(BorderFactory.createLineBorder(new Color (0,102,204), 03, rootPaneCheckingEnabled));
    }//GEN-LAST:event_txGajiLemburMouseEntered

    private void txGajiLemburMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txGajiLemburMouseExited
        lembur.setForeground(new Color (153,153,153));
        txGajiLembur.setBorder(BorderFactory.createLineBorder(new Color (204,204,204), 03, rootPaneCheckingEnabled));
    }//GEN-LAST:event_txGajiLemburMouseExited

    private void txGajiPokokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txGajiPokokMouseEntered
        pokok.setForeground(new Color (25,25,25));
        txGajiPokok.setBorder(BorderFactory.createLineBorder(new Color (0,102,204), 03, rootPaneCheckingEnabled));
    }//GEN-LAST:event_txGajiPokokMouseEntered

    private void txGajiPokokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txGajiPokokMouseExited
        pokok.setForeground(new Color (153,153,153));
        txGajiPokok.setBorder(BorderFactory.createLineBorder(new Color (204,204,204), 03, rootPaneCheckingEnabled));
    }//GEN-LAST:event_txGajiPokokMouseExited

    private void txJabatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txJabatanMouseEntered
        jabatan.setForeground(new Color (25,25,25));
    }//GEN-LAST:event_txJabatanMouseEntered

    private void txJabatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txJabatanMouseExited
        jabatan.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_txJabatanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_gaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SelamatDatang2;
    private javax.swing.JLabel SelamatDatang3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel lembur;
    private Custom_Palette_Class.PanelRound panelRound1;
    private Custom_Palette_Class.PanelRound panelRound2;
    private javax.swing.JLabel pokok;
    private javax.swing.JTable tabeldatajabatan;
    private javax.swing.JPanel tmblbatal;
    private javax.swing.JPanel tmblbatal1;
    private rojerusan.RSMaterialButtonRectangle tomboledit;
    private rojerusan.RSMaterialButtonRectangle tombolhapus;
    private rojerusan.RSMaterialButtonRectangle tombolreset;
    private rojerusan.RSMaterialButtonRectangle tombolsimpan;
    private javax.swing.JTextField txGajiLembur;
    private javax.swing.JTextField txGajiPokok;
    private javax.swing.JTextField txID;
    private javax.swing.JComboBox<String> txJabatan;
    // End of variables declaration//GEN-END:variables
}
