/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license

 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JLabel;

/**
 *
 * @author nizarislamudin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        getContentPane().setBackground(new Color(225, 225, 225));
    }

    private void setUnderLine(JLabel labelAsButton){
        Font font = labelAsButton.getFont();
        Map attribute = font.getAttributes();
        attribute.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        labelAsButton.setFont(font.deriveFont(attribute));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        buttonlgn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txPassword = new javax.swing.JPasswordField();
        txUsername = new javax.swing.JTextField();
        AksesAkunAnda = new javax.swing.JLabel();
        SelamatDatang = new javax.swing.JLabel();
        ButtonClose = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AksesAkunAnda1 = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        Username1 = new javax.swing.JLabel();
        Username2 = new javax.swing.JLabel();
        Illustration = new javax.swing.JPanel();
        IllustrationPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusTraversalPolicyProvider(true);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/income.png")).getImage()
        );
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LoginForm.setBackground(new java.awt.Color(0, 38, 165));
        LoginForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonlgn.setBackground(new java.awt.Color(69, 90, 100));
        buttonlgn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlgnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonlgnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonlgnMouseExited(evt);
            }
        });
        buttonlgn.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MASUK");
        buttonlgn.add(jLabel4, new java.awt.GridBagConstraints());

        txPassword.setBackground(new java.awt.Color(0, 38, 165));
        txPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txPassword.setForeground(new java.awt.Color(255, 255, 255));
        txPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPasswordActionPerformed(evt);
            }
        });

        txUsername.setBackground(new java.awt.Color(0, 38, 165));
        txUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txUsername.setForeground(new java.awt.Color(255, 255, 255));
        txUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsernameActionPerformed(evt);
            }
        });

        AksesAkunAnda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AksesAkunAnda.setForeground(new java.awt.Color(255, 255, 255));
        AksesAkunAnda.setText("Akses Akun Anda");

        SelamatDatang.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        SelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setText("Selamat Datang");

        ButtonClose.setBackground(new java.awt.Color(204, 0, 0));
        ButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClose.setPreferredSize(new java.awt.Dimension(40, 40));
        ButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCloseMouseClicked(evt);
            }
        });
        ButtonClose.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        ButtonClose.add(jLabel3, new java.awt.GridBagConstraints());

        AksesAkunAnda1.setForeground(new java.awt.Color(255, 255, 255));
        AksesAkunAnda1.setText("Belum punya akun?");

        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Mendaftar");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });

        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("Show Password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        Username1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username1.setForeground(new java.awt.Color(255, 255, 255));
        Username1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/padlock.png"))); // NOI18N

        Username2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username2.setForeground(new java.awt.Color(255, 255, 255));
        Username2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/user.png"))); // NOI18N

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(SelamatDatang))
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(AksesAkunAnda))
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addComponent(AksesAkunAnda1)
                        .addGap(3, 3, 3)
                        .addComponent(signup))
                    .addComponent(buttonlgn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LoginFormLayout.createSequentialGroup()
                            .addComponent(Username1)
                            .addGap(18, 18, 18)
                            .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LoginFormLayout.createSequentialGroup()
                            .addComponent(Username2)
                            .addGap(18, 18, 18)
                            .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(SelamatDatang)
                .addGap(0, 0, 0)
                .addComponent(AksesAkunAnda)
                .addGap(30, 30, 30)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username2))
                .addGap(41, 41, 41)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username1))
                .addGap(10, 10, 10)
                .addComponent(check)
                .addGap(22, 22, 22)
                .addComponent(buttonlgn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AksesAkunAnda1)
                    .addComponent(signup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Illustration.setBackground(new java.awt.Color(255, 255, 255));

        IllustrationPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/Tablet login-rafiki.png"))); // NOI18N
        IllustrationPic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout IllustrationLayout = new javax.swing.GroupLayout(Illustration);
        Illustration.setLayout(IllustrationLayout);
        IllustrationLayout.setHorizontalGroup(
            IllustrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IllustrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IllustrationPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IllustrationLayout.setVerticalGroup(
            IllustrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IllustrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IllustrationPic, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(Illustration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Illustration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonlgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlgnMouseClicked
        // TODO add your handling code here:
      try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM login WHERE Username='" + txUsername.getText()
                    +"' and Password='"+ txPassword.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()){
                JOptionPane.showMessageDialog(null, "Berhasil Masuk");
                if(r.getString("level").equals("ADMIN")){
                this.dispose();
                new menu_admin().setVisible(true);
                }else if(r.getString("level").equals("TELLER")){
                this.dispose();
                new menu_teller().setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Username Atau Password Salah");
                txPassword.requestFocus();
            }
        }catch(SQLException e){
            System.out.println("error");
        }
    }//GEN-LAST:event_buttonlgnMouseClicked

    private void buttonlgnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlgnMouseEntered
        // TODO add your handling code here:
        buttonlgn.setBackground(new Color (0,0,0));
    }//GEN-LAST:event_buttonlgnMouseEntered

    private void buttonlgnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlgnMouseExited
        // TODO add your handling code here:
        buttonlgn.setBackground(new Color (69,90,100));
    }//GEN-LAST:event_buttonlgnMouseExited

    private void txPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPasswordActionPerformed

    private void txUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsernameActionPerformed

    private void ButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCloseMouseClicked
        dispose();
    }//GEN-LAST:event_ButtonCloseMouseClicked

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
       setUnderLine(signup);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        signup.setFont(null);
    }//GEN-LAST:event_signupMouseExited

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        daftar_akun a = new daftar_akun();
        a.setVisible(true);
    }//GEN-LAST:event_signupMouseClicked

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if(check.isSelected())
        {
            txPassword.setEchoChar((char)0);
        }
        else
        {
            txPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoadingScreen.SplashScreen(null, true).setVisible(true);
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AksesAkunAnda;
    private javax.swing.JLabel AksesAkunAnda1;
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel Illustration;
    private javax.swing.JLabel IllustrationPic;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JPanel buttonlgn;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel signup;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
