/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;

/**
 *
 * @author nizarislamudin
 */
public class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public menu_admin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        menudropdowninformasi.setVisible(false);
        menudropdownakun.setVisible(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menudropdownakun = new javax.swing.JPanel();
        pnlkelola = new javax.swing.JPanel();
        Manage = new javax.swing.JLabel();
        pnlkeluar = new javax.swing.JPanel();
        Logout = new javax.swing.JLabel();
        menudropdowninformasi = new javax.swing.JPanel();
        pnljuknis = new javax.swing.JPanel();
        juknis = new javax.swing.JLabel();
        pnlabout = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        dropdowninformasi = new javax.swing.JLabel();
        menulaporan = new javax.swing.JLabel();
        menugaji = new javax.swing.JLabel();
        dropdownakun = new javax.swing.JLabel();
        menujabatan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menukaryawan = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/income.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menudropdownakun.setBackground(new java.awt.Color(0, 26, 114));
        menudropdownakun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menudropdownakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menudropdownakunMouseClicked(evt);
            }
        });

        pnlkelola.setBackground(new java.awt.Color(204, 204, 204));
        pnlkelola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlkelolaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlkelolaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlkelolaMouseExited(evt);
            }
        });
        pnlkelola.setLayout(new java.awt.GridBagLayout());

        Manage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Manage.setForeground(new java.awt.Color(0, 26, 114));
        Manage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Manage.setText("Kelola");
        pnlkelola.add(Manage, new java.awt.GridBagConstraints());

        pnlkeluar.setBackground(new java.awt.Color(204, 204, 204));
        pnlkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlkeluarMouseExited(evt);
            }
        });
        pnlkeluar.setLayout(new java.awt.GridBagLayout());

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(0, 26, 114));
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logout.setText("Keluar");
        pnlkeluar.add(Logout, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout menudropdownakunLayout = new javax.swing.GroupLayout(menudropdownakun);
        menudropdownakun.setLayout(menudropdownakunLayout);
        menudropdownakunLayout.setHorizontalGroup(
            menudropdownakunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlkelola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menudropdownakunLayout.setVerticalGroup(
            menudropdownakunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menudropdownakunLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(pnlkelola, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menudropdownakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 60, 82, 80));

        menudropdowninformasi.setBackground(new java.awt.Color(0, 26, 114));
        menudropdowninformasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menudropdowninformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menudropdowninformasiMouseClicked(evt);
            }
        });

        pnljuknis.setBackground(new java.awt.Color(204, 204, 204));
        pnljuknis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnljuknisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnljuknisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnljuknisMouseExited(evt);
            }
        });
        pnljuknis.setLayout(new java.awt.GridBagLayout());

        juknis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        juknis.setForeground(new java.awt.Color(0, 26, 114));
        juknis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juknis.setText("Juknis");
        pnljuknis.add(juknis, new java.awt.GridBagConstraints());

        pnlabout.setBackground(new java.awt.Color(204, 204, 204));
        pnlabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlaboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlaboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlaboutMouseExited(evt);
            }
        });
        pnlabout.setLayout(new java.awt.GridBagLayout());

        about.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        about.setForeground(new java.awt.Color(0, 26, 114));
        about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about.setText("Tentang");
        pnlabout.add(about, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout menudropdowninformasiLayout = new javax.swing.GroupLayout(menudropdowninformasi);
        menudropdowninformasi.setLayout(menudropdowninformasiLayout);
        menudropdowninformasiLayout.setHorizontalGroup(
            menudropdowninformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnljuknis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlabout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menudropdowninformasiLayout.setVerticalGroup(
            menudropdowninformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menudropdowninformasiLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(pnljuknis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlabout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menudropdowninformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 82, 80));

        dropdowninformasi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dropdowninformasi.setForeground(new java.awt.Color(255, 255, 255));
        dropdowninformasi.setText("Informasi");
        dropdowninformasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dropdowninformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdowninformasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdowninformasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dropdowninformasiMouseExited(evt);
            }
        });
        getContentPane().add(dropdowninformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, -1));

        menulaporan.setBackground(new java.awt.Color(255, 255, 255));
        menulaporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menulaporan.setForeground(new java.awt.Color(255, 255, 255));
        menulaporan.setText("Laporan");
        menulaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menulaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulaporanMouseExited(evt);
            }
        });
        getContentPane().add(menulaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        menugaji.setBackground(new java.awt.Color(255, 255, 255));
        menugaji.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menugaji.setForeground(new java.awt.Color(255, 255, 255));
        menugaji.setText("Input Gaji");
        menugaji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menugaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menugajiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menugajiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menugajiMouseExited(evt);
            }
        });
        getContentPane().add(menugaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        dropdownakun.setBackground(new java.awt.Color(255, 255, 255));
        dropdownakun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dropdownakun.setForeground(new java.awt.Color(255, 255, 255));
        dropdownakun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dropdownakun.setText("Akun");
        dropdownakun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dropdownakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropdownakunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dropdownakunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dropdownakunMouseExited(evt);
            }
        });
        getContentPane().add(dropdownakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 80, -1));

        menujabatan.setBackground(new java.awt.Color(255, 255, 255));
        menujabatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menujabatan.setForeground(new java.awt.Color(255, 255, 255));
        menujabatan.setText("Input Jabatan");
        menujabatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menujabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menujabatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menujabatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menujabatanMouseExited(evt);
            }
        });
        getContentPane().add(menujabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("PT. Bluescope. Indonesia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        jLabel2.setText("Penggajian Karyawan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Aplikasi Sistem Informasi Penggajian Karyawan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        menukaryawan.setBackground(new java.awt.Color(255, 255, 255));
        menukaryawan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menukaryawan.setForeground(new java.awt.Color(255, 255, 255));
        menukaryawan.setText("Input Karyawan");
        menukaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menukaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menukaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menukaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menukaryawanMouseExited(evt);
            }
        });
        getContentPane().add(menukaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAsset/Frame 2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menugajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menugajiMouseClicked
        input_gaji a = new input_gaji();
        a.setVisible(true);
    }//GEN-LAST:event_menugajiMouseClicked

    private void menugajiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menugajiMouseEntered
        menugaji.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_menugajiMouseEntered

    private void menugajiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menugajiMouseExited
        menugaji.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_menugajiMouseExited

    private void menulaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaporanMouseClicked
        laporan_gaji_admin a = new laporan_gaji_admin();
        a.setVisible(true);
    }//GEN-LAST:event_menulaporanMouseClicked

    private void menulaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaporanMouseEntered
        menulaporan.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_menulaporanMouseEntered

    private void menulaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaporanMouseExited
        menulaporan.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_menulaporanMouseExited

    private void menujabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menujabatanMouseClicked
        input_jabatan a = new input_jabatan();
        a.setVisible(true);
    }//GEN-LAST:event_menujabatanMouseClicked

    private void menujabatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menujabatanMouseEntered
        menujabatan.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_menujabatanMouseEntered

    private void menujabatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menujabatanMouseExited
        menujabatan.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_menujabatanMouseExited

    private void dropdownakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownakunMouseClicked
        menudropdownakun.setVisible(true);
    }//GEN-LAST:event_dropdownakunMouseClicked

    private void dropdownakunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownakunMouseEntered
        dropdownakun.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_dropdownakunMouseEntered

    private void dropdownakunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownakunMouseExited
        dropdownakun.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_dropdownakunMouseExited

    private void dropdowninformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdowninformasiMouseClicked
        menudropdowninformasi.setVisible(true);
    }//GEN-LAST:event_dropdowninformasiMouseClicked

    private void dropdowninformasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdowninformasiMouseEntered
        dropdowninformasi.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_dropdowninformasiMouseEntered

    private void dropdowninformasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdowninformasiMouseExited
        dropdowninformasi.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_dropdowninformasiMouseExited

    private void pnljuknisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnljuknisMouseClicked
        juknis a = new juknis();
        a.setVisible(true);
    }//GEN-LAST:event_pnljuknisMouseClicked

    private void pnljuknisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnljuknisMouseEntered
        pnljuknis.setBackground(new Color (0,26,114));
        juknis.setForeground(new Color (204,204,204));
    }//GEN-LAST:event_pnljuknisMouseEntered

    private void pnljuknisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnljuknisMouseExited
        pnljuknis.setBackground(new Color (204,204,204));
        juknis.setForeground(new Color (0,26,114));
    }//GEN-LAST:event_pnljuknisMouseExited

    private void pnlaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlaboutMouseClicked
        about_apps a = new about_apps();
        a.setVisible(true);
    }//GEN-LAST:event_pnlaboutMouseClicked

    private void pnlaboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlaboutMouseEntered
        pnlabout.setBackground(new Color (0,26,114));
        about.setForeground(new Color (204,204,204));
    }//GEN-LAST:event_pnlaboutMouseEntered

    private void pnlaboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlaboutMouseExited
        pnlabout.setBackground(new Color (204,204,204));
        about.setForeground(new Color (0,26,114));
    }//GEN-LAST:event_pnlaboutMouseExited

    private void menudropdowninformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menudropdowninformasiMouseClicked
        menudropdowninformasi.setVisible(false);
    }//GEN-LAST:event_menudropdowninformasiMouseClicked

    private void pnlkelolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkelolaMouseClicked
        kelola_akun a = new kelola_akun();
        a.setVisible(true);
    }//GEN-LAST:event_pnlkelolaMouseClicked

    private void pnlkelolaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkelolaMouseEntered
        pnlkelola.setBackground(new Color (0,26,114));
        Manage.setForeground(new Color (204,204,204));
    }//GEN-LAST:event_pnlkelolaMouseEntered

    private void pnlkelolaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkelolaMouseExited
        pnlkelola.setBackground(new Color (204,204,204));
        Manage.setForeground(new Color (0,26,114));
    }//GEN-LAST:event_pnlkelolaMouseExited

    private void pnlkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkeluarMouseClicked
        this.dispose();
        login a = new login();
        a.setVisible(true);
    }//GEN-LAST:event_pnlkeluarMouseClicked

    private void pnlkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkeluarMouseEntered
        pnlkeluar.setBackground(new Color (0,26,114));
        Logout.setForeground(new Color (204,204,204));
    }//GEN-LAST:event_pnlkeluarMouseEntered

    private void pnlkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkeluarMouseExited
        pnlkeluar.setBackground(new Color (204,204,204));
        Logout.setForeground(new Color (0,26,114));
    }//GEN-LAST:event_pnlkeluarMouseExited

    private void menudropdownakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menudropdownakunMouseClicked
        menudropdownakun.setVisible(false);
    }//GEN-LAST:event_menudropdownakunMouseClicked

    private void menukaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menukaryawanMouseClicked
        input_data_karyawan a = new input_data_karyawan();
        a.setVisible(true);
    }//GEN-LAST:event_menukaryawanMouseClicked

    private void menukaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menukaryawanMouseEntered
        menukaryawan.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_menukaryawanMouseEntered

    private void menukaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menukaryawanMouseExited
        menukaryawan.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_menukaryawanMouseExited
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Manage;
    private javax.swing.JLabel about;
    private javax.swing.JLabel dropdownakun;
    private javax.swing.JLabel dropdowninformasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel juknis;
    private javax.swing.JPanel menudropdownakun;
    private javax.swing.JPanel menudropdowninformasi;
    private javax.swing.JLabel menugaji;
    private javax.swing.JLabel menujabatan;
    private javax.swing.JLabel menukaryawan;
    private javax.swing.JLabel menulaporan;
    private javax.swing.JPanel pnlabout;
    private javax.swing.JPanel pnljuknis;
    private javax.swing.JPanel pnlkelola;
    private javax.swing.JPanel pnlkeluar;
    // End of variables declaration//GEN-END:variables
}
